spring.application.name=MCP Vega
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=andrei
spring.datasource.password=andrei
spring.ai.mcp.server.name=vega-mcp
spring.ai.mcp.server.version=1.0.0

#server.port=8080
#spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.protocol=STREAMABLE
#spring.ai.mcp.server.type=sync

#spring.main.web-application-type=none
#spring.main.banner-mode=off

##logging.level.root=OFF
#logging.level.root=OFF
#logging.file.name=mcp-server.log
#logging.level.com.andrei.mcpvega=DEBUG